import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/global/navbar/navbar";
import { Footer } from "@/components/global/footer/footer";
import localFont from "next/font/local";

const heroFont = localFont({
  src: [
    { path: "../public/fonts/aBlackLives.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/aBlackLives.otf", weight: "400", style: "italic" },
  ],
  display: "swap",
  variable: "--font-hero",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${heroFont.variable} antialiased flex flex-col`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
