/**
 * Business Configuration - Single Source of Truth
 * This file is AUTO-GENERATED from business.yaml
 * Run `python generate_rules.py` to regenerate
 * DO NOT EDIT THIS FILE DIRECTLY - Edit business.yaml instead
 */

export interface ServiceItem {
    name: string;
    url: string;
    description?: string;
  }

export interface ProductBrand {
    name: string;
    slug: string;
    url: string;
    lines?: ProductLine[];
    description?: string;
  }

export interface ProductLine {
    name: string;
    slug: string;
    description?: string;
  }

export interface ProductCategory {
    name: string;
    slug: string;
    url: string;
    description?: string;
    subCategories?: ProductCategory[];
  }

export interface ProductIndustry {
    name: string;
    slug: string;
    url: string;
    description?: string;
  }

export interface Product {
    id: string;
    name: string;
    slug: string;
    url: string;
    description?: string;
    image?: string;
    features?: string[];
    brand?: string;
    brandSlug?: string;
    line?: string;
    lineSlug?: string;
    category?: string;
    categorySlug?: string;
    industry?: string[];
    industrySlugs?: string[];
    series?: string;
    model?: string;
    // Additional fields for CMS integration
    [key: string]: unknown;
  }
  
  export interface Location {
    city: string;
    state: string;
    url?: string;
  }
  
  export interface ContactInfo {
    address: string;
    street: string;
    city: string;
    state: string;
    zip: string;
    areaCode: string;
    phone: string[];
    email: string[];
    addressVisibility: 'HIDDEN' | 'VISIBLE';
  }
  
  export interface SocialMedia {
    facebook?: string;
    twitter?: string;
    linkedin?: string;
    pinterest?: string;
    nextdoor?: string;
    yelp?: string;
    instagram?: string;
    youtube?: string;
    tiktok?: string;
  }
  
  export interface GoogleMaps {
    shortLink: string;
    fullUrl: string;
    embedCode: string;
    latitude: string;
    longitude: string;
  }
  
  export interface BusinessHours {
    weekdays: string;
    weekends: string;
  }

  

  // ==========================================
  // BUSINESS INFORMATION
  // ==========================================
  export const BUSINESS_INFO = {
    name: "Acogas ",
    websiteUrl: "https://www.acogas.pe",
    tone: "Professional",
    logoUrl: "/assets/config/logo.png",
    tagline: "Soluciones industriales seguras y eficientes en GLP, Gas Natural, Vapor y Procesos Especiales.",
    primaryKeyword: "Productos para la Industria, Gas y Energía",
    ctaText: "Solicitar visita técnica especializada",
  } as const;
  
  // ==========================================
  // BUSINESS CATEGORIES
  // ==========================================
  export const BUSINESS_CATEGORIES = {
    primary: "Productos para la Industria, Gas y Energía",
    secondary: [
      "GLP",
      "Gas Natural",
      "Vapor",
      "Procesos Especiales",
    ],
  } as const;
  
  // ==========================================
  // CORE SERVICES
  // ==========================================
  export const CORE_SERVICES: ServiceItem[] = [
    {
      name: "Ingeniería y Dimensionamiento",
      url: "/servicios/ingenieria-dimensionamiento/",
      description: "Servicios de ingeniería y dimensionamiento técnico para soluciones industriales",
    },
    {
      name: "Selección de Equipos",
      url: "/servicios/seleccion-equipos/",
      description: "Asesoría especializada en selección de equipos industriales",
    },
    {
      name: "Diagnóstico Técnico",
      url: "/servicios/diagnostico-tecnico/",
      description: "Diagnóstico técnico especializado para sistemas industriales",
    },
    {
      name: "Soporte Técnico",
      url: "/servicios/soporte-tecnico/",
      description: "Soporte técnico continuo para equipos y sistemas",
    },
    {
      name: "Mantenimiento Industrial",
      url: "/servicios/mantenimiento-industrial/",
      description: "Servicios de mantenimiento industrial preventivo y correctivo",
    },
  ];
  
  // Flattened arrays for quick access
  export const CORE_SERVICE_NAMES = CORE_SERVICES.map(s => s.name);
  export const CORE_SERVICE_URLS = CORE_SERVICES.map(s => s.url);
  
  // ==========================================
  // PRODUCT BRANDS
  // ==========================================
  export const PRODUCT_BRANDS: ProductBrand[] = [
    {
      name: "Emerson",
      slug: "emerson",
      url: "/marcas/emerson/",
      description: "Soluciones industriales de alta calidad",
      lines: [
        { name: "Fisher", slug: "fisher", description: "Fisher GLP y Gas Natural" },
        { name: "Tartarini", slug: "tartarini", description: "GN Avanzado" },
        { name: "Cash", slug: "cash", description: "Procesos" },
        { name: "Spence", slug: "spence", description: "Vapor" },
      ],
    },
    {
      name: "Corken",
      slug: "corken",
      url: "/marcas/corken/",
      description: "Bombas y compresores para GLP y Gas Natural",
      lines: [
        { name: "GLP / GN", slug: "glp-gn", description: "Bombas y compresores" },
      ],
    },
    {
      name: "Cavagna",
      slug: "cavagna",
      url: "/marcas/cavagna/",
      description: "Reguladores para GLP y Gas Natural",
      lines: [
        { name: "GLP / GN", slug: "glp-gn", description: "Reguladores" },
      ],
    },
    {
      name: "Liquid Controls",
      slug: "liquid-controls",
      url: "/marcas/liquid-controls/",
      description: "Medición y control de fluidos",
      lines: [
        { name: "Medición", slug: "medicion", description: "Medidores" },
      ],
    },
  ];

  // Helper arrays for quick access
  export const PRODUCT_BRAND_NAMES = PRODUCT_BRANDS.map(b => b.name);
  export const PRODUCT_BRAND_SLUGS = PRODUCT_BRANDS.map(b => b.slug);
  export const PRODUCT_BRAND_URLS = PRODUCT_BRANDS.map(b => b.url);

  // ==========================================
  // PRODUCT CATEGORIES (Hierarchical)
  // ==========================================
  export const PRODUCT_CATEGORIES: ProductCategory[] = [
    {
      name: "Regulación y Control de Presión",
      slug: "regulacion-control-presion",
      url: "/productos/regulacion-control-presion/",
      description: "Equipos de regulación y control de presión industrial",
      subCategories: [
        {
          name: "Reguladores de Presión",
          slug: "reguladores-presion",
          url: "/productos/regulacion-control-presion/reguladores-presion/",
          subCategories: [
            {
              name: "Reguladores de presión industriales",
              slug: "reguladores-presion-industriales",
              url: "/productos/regulacion-control-presion/reguladores-presion-industriales/",
            },
            {
              name: "Reguladores de acción directa",
              slug: "reguladores-accion-directa",
              url: "/productos/regulacion-control-presion/reguladores-accion-directa/",
            },
            {
              name: "Reguladores cargados por resorte",
              slug: "reguladores-cargados-resorte",
              url: "/productos/regulacion-control-presion/reguladores-cargados-resorte/",
            },
            {
              name: "Reguladores piloto-operados",
              slug: "reguladores-piloto-operados",
              url: "/productos/regulacion-control-presion/reguladores-piloto-operados/",
            },
          ],
        },
        {
          name: "Válvulas de Control",
          slug: "valvulas-control",
          url: "/productos/regulacion-control-presion/valvulas-control/",
          subCategories: [
            {
              name: "Válvulas de control industriales",
              slug: "valvulas-control-industriales",
              url: "/productos/regulacion-control-presion/valvulas-control-industriales/",
            },
            {
              name: "Válvulas de control para gas",
              slug: "valvulas-control-gas",
              url: "/productos/regulacion-control-presion/valvulas-control-gas/",
            },
            {
              name: "Válvulas de control para vapor",
              slug: "valvulas-control-vapor",
              url: "/productos/regulacion-control-presion/valvulas-control-vapor/",
            },
          ],
        },
        {
          name: "Estaciones de Regulación",
          slug: "estaciones-regulacion",
          url: "/productos/regulacion-control-presion/estaciones-regulacion/",
          subCategories: [
            {
              name: "Estaciones de regulación de gas",
              slug: "estaciones-regulacion-gas",
              url: "/productos/regulacion-control-presion/estaciones-regulacion-gas/",
            },
            {
              name: "Estaciones de regulación y medición",
              slug: "estaciones-regulacion-medicion",
              url: "/productos/regulacion-control-presion/estaciones-regulacion-medicion/",
            },
          ],
        },
      ],
    },
    {
      name: "Medición y Control de Flujo",
      slug: "medicion-control-flujo",
      url: "/productos/medicion-control-flujo/",
      description: "Sistemas de medición y control de flujo",
      subCategories: [
        {
          name: "Medidores Industriales",
          slug: "medidores-industriales",
          url: "/productos/medicion-control-flujo/medidores-industriales/",
          subCategories: [
            {
              name: "Medidores de caudal",
              slug: "medidores-caudal",
              url: "/productos/medicion-control-flujo/medidores-caudal/",
            },
            {
              name: "Medidores volumétricos",
              slug: "medidores-volumetricos",
              url: "/productos/medicion-control-flujo/medidores-volumetricos/",
            },
          ],
        },
        {
          name: "Sistemas de Medición",
          slug: "sistemas-medicion",
          url: "/productos/medicion-control-flujo/sistemas-medicion/",
          subCategories: [
            {
              name: "Skids de medición",
              slug: "skids-medicion",
              url: "/productos/medicion-control-flujo/skids-medicion/",
            },
            {
              name: "Sistemas integrados de medición",
              slug: "sistemas-integrados-medicion",
              url: "/productos/medicion-control-flujo/sistemas-integrados-medicion/",
            },
          ],
        },
        {
          name: "Accesorios de Medición",
          slug: "accesorios-medicion",
          url: "/productos/medicion-control-flujo/accesorios-medicion/",
          subCategories: [
            {
              name: "Transmisores",
              slug: "transmisores",
              url: "/productos/medicion-control-flujo/transmisores/",
            },
            {
              name: "Indicadores y registradores",
              slug: "indicadores-registradores",
              url: "/productos/medicion-control-flujo/indicadores-registradores/",
            },
          ],
        },
      ],
    },
    {
      name: "Vapor y Procesos Térmicos",
      slug: "vapor-procesos-termicos",
      url: "/productos/vapor-procesos-termicos/",
      description: "Equipos para sistemas de vapor y procesos térmicos",
      subCategories: [
        {
          name: "Regulación de Vapor",
          slug: "regulacion-vapor",
          url: "/productos/vapor-procesos-termicos/regulacion-vapor/",
          subCategories: [
            {
              name: "Reguladores de vapor",
              slug: "reguladores-vapor",
              url: "/productos/vapor-procesos-termicos/reguladores-vapor/",
            },
            {
              name: "Válvulas reductoras de presión",
              slug: "valvulas-reductoras-presion",
              url: "/productos/vapor-procesos-termicos/valvulas-reductoras-presion/",
            },
          ],
        },
        {
          name: "Trampas de Vapor",
          slug: "trampas-vapor",
          url: "/productos/vapor-procesos-termicos/trampas-vapor/",
          subCategories: [
            {
              name: "Trampas mecánicas",
              slug: "trampas-mecanicas",
              url: "/productos/vapor-procesos-termicos/trampas-mecanicas/",
            },
            {
              name: "Trampas termodinámicas",
              slug: "trampas-termodinamicas",
              url: "/productos/vapor-procesos-termicos/trampas-termodinamicas/",
            },
          ],
        },
        {
          name: "Accesorios para Vapor",
          slug: "accesorios-vapor",
          url: "/productos/vapor-procesos-termicos/accesorios-vapor/",
          subCategories: [
            {
              name: "Separadores",
              slug: "separadores",
              url: "/productos/vapor-procesos-termicos/separadores/",
            },
            {
              name: "Filtros",
              slug: "filtros",
              url: "/productos/vapor-procesos-termicos/filtros/",
            },
            {
              name: "Válvulas de seguridad",
              slug: "valvulas-seguridad",
              url: "/productos/vapor-procesos-termicos/valvulas-seguridad/",
            },
          ],
        },
      ],
    },
    {
      name: "Bombas y Compresores",
      slug: "bombas-compresores",
      url: "/productos/bombas-compresores/",
      description: "Bombas y compresores industriales",
      subCategories: [
        {
          name: "Bombas Industriales",
          slug: "bombas-industriales",
          url: "/productos/bombas-compresores/bombas-industriales/",
          subCategories: [
            {
              name: "Bombas para GLP",
              slug: "bombas-glp",
              url: "/productos/bombas-compresores/bombas-glp/",
            },
            {
              name: "Bombas para fluidos industriales",
              slug: "bombas-fluidos-industriales",
              url: "/productos/bombas-compresores/bombas-fluidos-industriales/",
            },
          ],
        },
        {
          name: "Compresores Industriales",
          slug: "compresores-industriales",
          url: "/productos/bombas-compresores/compresores-industriales/",
          subCategories: [
            {
              name: "Compresores para gas",
              slug: "compresores-gas",
              url: "/productos/bombas-compresores/compresores-gas/",
            },
            {
              name: "Compresores para aplicaciones especiales",
              slug: "compresores-aplicaciones-especiales",
              url: "/productos/bombas-compresores/compresores-aplicaciones-especiales/",
            },
          ],
        },
      ],
    },
    {
      name: "Seguridad y Alivio de Presión",
      slug: "seguridad-alivio-presion",
      url: "/productos/seguridad-alivio-presion/",
      description: "Equipos de seguridad y alivio de presión",
      subCategories: [
        {
          name: "Válvulas de Seguridad",
          slug: "valvulas-seguridad",
          url: "/productos/seguridad-alivio-presion/valvulas-seguridad/",
          subCategories: [
            {
              name: "Válvulas de alivio",
              slug: "valvulas-alivio",
              url: "/productos/seguridad-alivio-presion/valvulas-alivio/",
            },
            {
              name: "Válvulas de seguridad certificadas",
              slug: "valvulas-seguridad-certificadas",
              url: "/productos/seguridad-alivio-presion/valvulas-seguridad-certificadas/",
            },
          ],
        },
        {
          name: "Sistemas de Protección",
          slug: "sistemas-proteccion",
          url: "/productos/seguridad-alivio-presion/sistemas-proteccion/",
          subCategories: [
            {
              name: "Protección contra sobrepresión",
              slug: "proteccion-sobrepresion",
              url: "/productos/seguridad-alivio-presion/proteccion-sobrepresion/",
            },
            {
              name: "Sistemas de seguridad industrial",
              slug: "sistemas-seguridad-industrial",
              url: "/productos/seguridad-alivio-presion/sistemas-seguridad-industrial/",
            },
          ],
        },
      ],
    },
    {
      name: "Procesos Especiales y Multifluidos",
      slug: "procesos-especiales-multifluidos",
      url: "/productos/procesos-especiales-multifluidos/",
      description: "Equipos para procesos especiales y múltiples fluidos",
      subCategories: [
        {
          name: "Regulación de Gas Natural",
          slug: "regulacion-gas-natural",
          url: "/productos/procesos-especiales-multifluidos/regulacion-gas-natural/",
        },
        {
          name: "Regulación de GLP",
          slug: "regulacion-glp",
          url: "/productos/procesos-especiales-multifluidos/regulacion-glp/",
        },
        {
          name: "Regulación de Aire",
          slug: "regulacion-aire",
          url: "/productos/procesos-especiales-multifluidos/regulacion-aire/",
        },
        {
          name: "Regulación de Agua",
          slug: "regulacion-agua",
          url: "/productos/procesos-especiales-multifluidos/regulacion-agua/",
        },
        {
          name: "Regulación de Otros Fluidos",
          slug: "regulacion-otros-fluidos",
          url: "/productos/procesos-especiales-multifluidos/regulacion-otros-fluidos/",
        },
      ],
    },
  ];

  // Helper to get top-level categories only
  export const TOP_LEVEL_CATEGORIES = PRODUCT_CATEGORIES.map(cat => ({
    name: cat.name,
    slug: cat.slug,
    url: cat.url,
    description: cat.description,
  }));

  // Helper to flatten all categories (for search/filtering)
  export const ALL_CATEGORIES = (function flatten(categories: ProductCategory[]): ProductCategory[] {
    return categories.flatMap(cat => [cat, ...(cat.subCategories ? flatten(cat.subCategories) : [])]);
  })(PRODUCT_CATEGORIES);

  // ==========================================
  // PRODUCT INDUSTRIES
  // ==========================================
  export const PRODUCT_INDUSTRIES: ProductIndustry[] = [
    {
      name: "Alimentos y Bebidas",
      slug: "alimentos-bebidas",
      url: "/industrias/alimentos-bebidas/",
      description: "Soluciones para la industria alimentaria y de bebidas",
    },
    {
      name: "Pesquera",
      slug: "pesquera",
      url: "/industrias/pesquera/",
      description: "Equipos para la industria pesquera",
    },
    {
      name: "Agroindustria",
      slug: "agroindustria",
      url: "/industrias/agroindustria/",
      description: "Soluciones para agroindustria",
    },
    {
      name: "Minería",
      slug: "mineria",
      url: "/industrias/mineria/",
      description: "Equipos para la industria minera",
    },
    {
      name: "Papel y Cartón",
      slug: "papel-carton",
      url: "/industrias/papel-carton/",
      description: "Soluciones para la industria del papel y cartón",
    },
    {
      name: "Industria General",
      slug: "industria-general",
      url: "/industrias/industria-general/",
      description: "Soluciones para industria general",
    },
  ];

  // Helper arrays for quick access
  export const PRODUCT_INDUSTRY_NAMES = PRODUCT_INDUSTRIES.map(i => i.name);
  export const PRODUCT_INDUSTRY_SLUGS = PRODUCT_INDUSTRIES.map(i => i.slug);
  export const PRODUCT_INDUSTRY_URLS = PRODUCT_INDUSTRIES.map(i => i.url);

  // ==========================================
  // CORE PRODUCTS (Dynamic - from CMS)
  // ==========================================
  // This will be populated from CMS
  // Structure is defined here for type safety
  export const CORE_PRODUCTS: Product[] = [];
  
  // Helper arrays (will be populated when CMS data is available)
  export const CORE_PRODUCT_NAMES = CORE_PRODUCTS.map(p => p.name);
  export const CORE_PRODUCT_SLUGS = CORE_PRODUCTS.map(p => p.slug);
  export const CORE_PRODUCT_URLS = CORE_PRODUCTS.map(p => p.url);

  // ==========================================
  // SERVICE AREAS / LOCATIONS
  // ==========================================
  export const LOCATIONS: Location[] = [
    { city: "Lima", state: "Lima", url: "/lima-peru/" },
   
  ];
  
  // Helper to get top locations (first 4)
  export const TOP_LOCATIONS = LOCATIONS.slice(0, 4);
  
  // Helper to format location string
  export const formatLocation = (location: Location): string => 
    `${location.city}, ${location.state}`;
  


  // ==========================================
  // CONTACT INFORMATION
  // ==========================================
  export const CONTACT: ContactInfo = {
    address: "Av La Encalada 1471, Santiago de Surco Lima 15023",
    street: "Av. La Encalada 1471 ",
    city: "Santiago de Surco",
    state: "Lima",
    zip: "15023",
    areaCode: "51",
    phone: ["998345895", "994296627"],
    email: ["acogas@acogas.pe", "ventas@acogas.pe"],
    addressVisibility: "VISIBLE", // SAB (Service Area Business)
  };

  
  // ==========================================
  // BUSINESS HOURS
  // ==========================================
  export const BUSINESS_HOURS: BusinessHours = {
    weekdays: "8:00 AM - 10:00 PM",
    weekends: "8:00 AM - 10:00 PM",
  };
  
  // Helper to format business hours for schema
  export const BUSINESS_HOURS_SCHEMA = "Lu-Vi 09:00-17:00";
  
  // ==========================================
  // GOOGLE MAPS
  // ==========================================
  export const GOOGLE_MAPS: GoogleMaps = {
    shortLink: "https://maps.app.goo.gl/MNin6HcLspbfDdz96",
    fullUrl: "https://www.google.com/maps/place/ACOGAS+%7C+Soluciones+Industriales+para+GLP,+GN+y+Vapor/@-12.1022724,-76.9731357,819m/data=!3m1!1e3!4m6!3m5!1s0x9105c94ed03b03db:0x2d69082002bce007!8m2!3d-12.1022777!4d-76.9705608!16s%2Fg%2F11bztdf6yf!5m1!1e3?entry=ttu&g_ep=EgoyMDI2MDEyNS4wIKXMDSoKLDEwMDc5MjA2N0gBUAM%3D",
    embedCode: `<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3565.889710174995!2d-76.9731357!3d-12.1022724!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c94ed03b03db%3A0x2d69082002bce007!2sACOGAS%20%7C%20Soluciones%20Industriales%20para%20GLP%2C%20GN%20y%20Vapor!5e1!3m2!1ses!2spe!4v1769615451800!5m2!1ses!2spe" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
    latitude: "29.8338937",
    longitude: "-95.5032244",
  };
  
  // ==========================================
  // SOCIAL MEDIA
  // ==========================================
  export const SOCIAL_MEDIA: SocialMedia = {
    facebook: "https://www.facebook.com/acogasperu",
    youtube: "https://www.youtube.com/channel/UCHeu5zubgt7D0ckJgWxb9OQ",
    linkedin: "https://www.linkedin.com/company/acogas/",
    tiktok: "https://www.tiktok.com/@acogas.industrial",
    instagram: "https://www.instagram.com/acogas.industrial/",

  };
  
  // Filter out undefined social media links
  export const ACTIVE_SOCIAL_MEDIA = Object.entries(SOCIAL_MEDIA)
    .filter(([_, url]) => url)
    .reduce((acc, [key, url]) => ({ ...acc, [key]: url }), {}) as SocialMedia;
  
  // ==========================================
  // BLOG TOPICS
  // ==========================================
  export const BLOG_TOPICS = [
    "Garage Door Maintenance Tips",
    "Garage Door Safety",
    "Choosing the Right Garage Door",
    "Garage Door Opener Installation",
    "Emergency Garage Door Repair"
  ] as const;
  
  // ==========================================
  // META INFORMATION
  // ==========================================
  export const META = {
    title: "Oak Forest Garage Doors - Expert Garage Door Services in Houston, TX",
    description: "Professional garage door installation, repair, and maintenance in Houston, TX and surrounding areas. Expert technicians, quality service, and customer satisfaction guaranteed. Contact us today for a free consultation!",
    keywords: "garage door services, garage door repair, garage door installation, Houston TX, garage door opener, emergency garage door repair",
  } as const;
  
  // ==========================================
  // ABOUT PAGE CONTENT
  // ==========================================
  export interface AboutStat {
    value: number;
    suffix: string;
    label: string;
  }
  
  export interface AboutValue {
    title: string;
    description: string;
  }
  
  export interface AboutHeader {
    badgeText: string;
    title: string;
    titleHighlight: string;
    description: string;
    primaryButtonText: string;
    secondaryButtonText: string;
    secondaryButtonLink: string;
    awardCardTitle: string;
    awardCardDescription: string;
    headerImage: string;
    headerImageAlt: string;
  }
  
  export interface AboutStory {
    title: string;
    paragraph1: string;
    paragraph2: string;
    paragraph3: string;
    image: string;
    imageAlt: string;
  }
  
  export interface AboutMissionValues {
    title: string;
    description: string;
    values: AboutValue[];
  }
  
  export interface AboutPageHeader {
    title: string;
    description: string;
    badges: string[];
  }
  
  export const ABOUT_HEADER: AboutHeader = {
    badgeText: "About Oak Forest Garage Doors",
    title: "Professional Garage Door Services with",
    titleHighlight: "Expert Solutions",
    description: "The truth is, we&apos;ve been providing professional garage door services for over a decade, and the thing is, our passion shows in every project we complete. Besides our expert installations, we specialize in repairs and maintenance that keep your garage doors operating smoothly for years.",
    primaryButtonText: "Get Free Consultation",
    secondaryButtonText: "View Our Work",
    secondaryButtonLink: "/project-gallery",
    awardCardTitle: "Award-Winning Service",
    awardCardDescription: "Recognized for excellence in Houston, Sugar Land, Katy, Cypress, and surrounding areas",
    headerImage: "/assets/config/placeholder-image.png",
    headerImageAlt: "Professional garage door installation team at work",
  };
  
  export const ABOUT_STATS: AboutStat[] = [
    { value: 150, suffix: "+", label: "Projects Completed" },
    { value: 1200, suffix: "+", label: "Happy Clients" },
    { value: 10, suffix: "+", label: "Years Experience" },
    { value: 98, suffix: "%", label: "Satisfaction Rate" }
  ];
  
  export const ABOUT_STORY: AboutStory = {
    title: "Our Story",
    paragraph1: "Oak Forest Garage Doors was founded with a simple mission: to provide reliable, professional garage door services that enhance our clients&apos; properties and increase their value.",
    paragraph2: "With over 10 years of experience, we&apos;ve built our reputation on quality craftsmanship, expert installations, and exceptional customer service. Our team of certified professionals brings expertise in installation, repair, maintenance, and comprehensive support services.",
    paragraph3: "We&apos;re proud to serve Houston, Sugar Land, Katy, Cypress, The Woodlands, and surrounding communities, providing solutions that are reliable, secure, and built to last.",
    image: "/assets/images/portfolio/oak-forest-garage-doors-18.webp",
    imageAlt: "Oak Forest Garage Doors team at work",
  };
  
  export const ABOUT_MISSION_VALUES: AboutMissionValues = {
    title: "Our Mission & Values",
    description: "We&apos;re committed to creating sustainable, beautiful garage door solutions while providing exceptional service to our community.",
    values: [
    { title: "Quality Craftsmanship", description: "We use premium materials and proven techniques to ensure every project meets our high standards." },
    { title: "Expert Team", description: "Our certified professionals bring years of experience and specialized knowledge to every project." },
    { title: "Local Expertise", description: "We understand local climate and conditions, ensuring your garage doors thrive year-round." }
    ],
  };
  
  export const ABOUT_PAGE_HEADER: AboutPageHeader = {
    title: "About Oak Forest Garage Doors",
    description: "Because we want you to know us",
    badges: [
      "Local Expertise",
      "Free Consultation",
      "Satisfaction Guaranteed"
    ],
  };
  
  // ==========================================
  // SERVICES PAGE CONTENT
  // ==========================================
  export interface ServicesPageHeader {
    title: string;
    subtitle: string;
    description: string;
  }
  
  export interface ServicesPageIntroduction {
    title: string;
    paragraph: string;
  }
  
  export interface ServicesPageSections {
    coreServicesTitle: string;
    specializedServicesTitle: string;
  }
  
  export interface ServicesPageContent {
    header: ServicesPageHeader;
    introduction: ServicesPageIntroduction;
    sections: ServicesPageSections;
  }
  
  export const SERVICES_PAGE_CONTENT: ServicesPageContent = {
    header: {
      title: "Oak Forest Garage Doors: Professional Garage Door Services Services",
      subtitle: "Get to know our services",
      description: "Complete solutions for installation, repair, maintenance, and replacement",
    },
    introduction: {
      title: "Comprehensive Garage Door Services Solutions",
      paragraph: "We&apos;re your one-stop shop for all garage door needs. From brand new installations to emergency repairs, routine maintenance to complete replacements, our expert team delivers professional service you can trust. Besides our extensive experience, the thing is, we treat every project with the care and attention it deserves.",
    },
    sections: {
      coreServicesTitle: "Core Services",
      specializedServicesTitle: "Specialized Services",
    },
  };
  
  // ==========================================
  // HELPER FUNCTIONS
  // ==========================================
  
  /**
   * Get services formatted for navigation/footer
   */
  /*
  export const getServicesForNavigation = () => {
    return CORE_SERVICES.map(service => ({
      name: service.name,
      href: service.url,
    }));
  };
  */
  /**
   * Get locations formatted for navigation/footer
   */
  /*
  export const getLocationsForNavigation = (limit?: number) => {
    const locs = limit ? LOCATIONS.slice(0, limit) : LOCATIONS;
    return locs.map(location => ({
      name: formatLocation(location),
      href: location.url || `/${location.city.toLowerCase().replace(/\s+/g, '-')}-${location.state.toLowerCase()}/`,
    }));
  };
  */
  /**
   * Get company links for footer/navigation
   */
  export const getCompanyLinks = () => [
    { name: "Nosotros", href: "/nosotros/" },
    { name: "Contacto", href: "/contacto/" },
    { name: "Productos", href: "/productos/" },
    { name: "Marcas", href: "/marcas/" },
  ];
  
  /**
   * Get legal links for footer
   */
  export const getLegalLinks = () => [
    { name: "Política de Privacidad", href: "/politica-de-privacidad/" },
    { name: "Términos y Condiciones", href: "/terminos-y-condiciones/" },
  ];
  
  /**
   * Format phone number for display (281-867-6660)
   */
  export const formatPhoneDisplay = (phone: string): string => {
    const digits = phone.replace(/\D/g, '');
    if (digits.length === 9) {
      return `+51 ${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}`;
    }
    if (digits.length === 11 && digits.startsWith('51')) {
      const withoutCountryCode = digits.slice(1);
      return `${withoutCountryCode.slice(0, 3)}-${withoutCountryCode.slice(3, 6)}-${withoutCountryCode.slice(6)}`;
    }
    return phone;
  };
  
  /**
   * Format phone number for tel: links (+15551234567)
   */
  export const formatPhoneTel = (phone: string): string => {
    const digits = phone.replace(/\D/g, '');
    if (digits.length === 10) {
      return `+51${digits}`;
    }
    if (digits.length === 11 && digits.startsWith('51')) {
      return `+${digits}`;
    }
    if (phone.startsWith('+')) {
      return phone;
    }
    return `+51${digits}`;
  };
  
export const getPhoneDisplay = (): string => formatPhoneDisplay(CONTACT.phone[0]);
  export const getPhoneTel = (): string => formatPhoneTel(CONTACT.phone[0]);
  export const getEmail = (): string => CONTACT.email[0];
  export const getBusinessHours = (): BusinessHours => BUSINESS_HOURS;
  export const getBusinessHoursForDay = (day: keyof BusinessHours): string => BUSINESS_HOURS[day];
  export const getSocialLinks = (): SocialMedia => ACTIVE_SOCIAL_MEDIA;
  export const getSocialLink = (platform: keyof SocialMedia): string | undefined => ACTIVE_SOCIAL_MEDIA[platform];
  export const getAddress = (): string => CONTACT.address;
  export const getCityState = (): string => `${CONTACT.city}, ${CONTACT.state}`;
  export const getGoogleMapsLink = (): string => GOOGLE_MAPS.shortLink;
  export const getGoogleMapsUrl = (): string => GOOGLE_MAPS.fullUrl;
  export const getBusinessName = (): string => BUSINESS_INFO.name;
  export const getTagline = (): string => BUSINESS_INFO.tagline;
  export const getPrimaryKeyword = (): string => BUSINESS_INFO.primaryKeyword;
  export const getWebsiteUrl = (): string => BUSINESS_INFO.websiteUrl;
  export const getLocationsString = (limit?: number): string => {
    const locs = limit ? LOCATIONS.slice(0, limit) : LOCATIONS;
    return locs.map(loc => formatLocation(loc)).join(', ');
  };
  
  export const getTopLocations = (count: number = 4): Location[] => LOCATIONS.slice(0, count);
  
  export const getPrimaryLocation = (): Location => LOCATIONS[0];
  // ==========================================
  // PRODUCT & SERVICE HELPER FUNCTIONS
  // ==========================================
  
  export const getServiceByName = (serviceName: string): ServiceItem | undefined => {
    return CORE_SERVICES.find(service => service.name === serviceName);
  };
  
  export const getServiceByUrl = (url: string): ServiceItem | undefined => {
    return CORE_SERVICES.find(service => service.url === url);
  };

  export const getBrandBySlug = (slug: string): ProductBrand | undefined => {
    return PRODUCT_BRANDS.find(brand => brand.slug === slug);
  };

  export const getBrandByUrl = (url: string): ProductBrand | undefined => {
    return PRODUCT_BRANDS.find(brand => brand.url === url);
  };

  export const getCategoryBySlug = (slug: string): ProductCategory | undefined => {
    return ALL_CATEGORIES.find(cat => cat.slug === slug);
  };

  export const getCategoryByUrl = (url: string): ProductCategory | undefined => {
    return ALL_CATEGORIES.find(cat => cat.url === url);
  };

  export const getTopLevelCategoryBySlug = (slug: string): ProductCategory | undefined => {
    return PRODUCT_CATEGORIES.find(cat => cat.slug === slug);
  };

  export const getIndustryBySlug = (slug: string): ProductIndustry | undefined => {
    return PRODUCT_INDUSTRIES.find(industry => industry.slug === slug);
  };

  export const getIndustryByUrl = (url: string): ProductIndustry | undefined => {
    return PRODUCT_INDUSTRIES.find(industry => industry.url === url);
  };

  export const getProductBySlug = (slug: string): Product | undefined => {
    return CORE_PRODUCTS.find(product => product.slug === slug);
  };

  export const getProductByUrl = (url: string): Product | undefined => {
    return CORE_PRODUCTS.find(product => product.url === url);
  };

  export const getProductsByBrand = (brandSlug: string): Product[] => {
    return CORE_PRODUCTS.filter(product => product.brandSlug === brandSlug);
  };

  export const getProductsByCategory = (categorySlug: string): Product[] => {
    return CORE_PRODUCTS.filter(product => product.categorySlug === categorySlug);
  };

  export const getProductsByIndustry = (industrySlug: string): Product[] => {
    return CORE_PRODUCTS.filter(product => 
      product.industrySlugs?.includes(industrySlug)
    );
  };

  export const getProductsByLine = (brandSlug: string, lineSlug: string): Product[] => {
    return CORE_PRODUCTS.filter(product => 
      product.brandSlug === brandSlug && product.lineSlug === lineSlug
    );
  };

  /*
  export const servesLocation = (city: string, state?: string): boolean => {
    if (state) {
      return LOCATIONS.some(loc => 
        loc.city.toLowerCase() === city.toLowerCase() && 
        loc.state.toLowerCase() === state.toLowerCase()
      );
    }
    return LOCATIONS.some(loc => loc.city.toLowerCase() === city.toLowerCase());
  };
  */
  export const getMetaInfo = () => ({
    title: META.title,
    description: META.description,
    keywords: META.keywords,
  });
  export const getBlogTopics = (): readonly string[] => BLOG_TOPICS;
  export const getCopyright = (): string => `© ${new Date().getFullYear()} ${BUSINESS_INFO.name}. All rights reserved.`;
  export const getBusinessCategories = () => BUSINESS_CATEGORIES;
  export const getBusinessDescription = (): string => {
    return `Soluciones industriales seguras y eficientes en GLP, Gas Natural, Vapor y Procesos Especiales.`;
  };
  export const getContactInfo = () => ({
    phone: getPhoneDisplay(),
    email: getEmail(),
    address: getAddress(),
  });
  export const getSocialLinksFormatted = () => {
    return Object.entries(ACTIVE_SOCIAL_MEDIA).map(([key, href]) => ({
      name: key.charAt(0).toUpperCase() + key.slice(1),
      href: href as string,
      key: key as keyof SocialMedia,
    }));
  };
  export const getDefaultAddresses = () => [
    {
      location: getCityState(),
      address: getAddress(),
    }
  ];
  export const getDefaultMapLocation = () => ({
    id: "main-location",
    name: getCityState(),
    address: getAddress(),
    mapEmbed: GOOGLE_MAPS.embedCode.match(/src="([^"]*)"/)?.[1] || "",
    mapTitle: `${getBusinessName()} ${getCityState()} Location`,
    isMain: true as const,
  });
  